### ISSUE TITLE
routing 추가 및 404페이지 추가시에 고려할 것 질문

### ISSUE THREAD

**Issue by kwonsuhyuk** [Node-study-programmers/catch_mind#4]
### - 인게임 라우팅에서 방 입장해서 대기하는 페이지랑 게임 진행시 페이지 같게 해야 하는지??

``` tsx
// 인게임 라우팅 부분
{
      path: "/ingame/:roomId",
      element: <InGame />,
 },
```

**Comment by nyh98** [comment]
페이지를 하나로 해서 게임 대기와 시작을 상태관리로 하는게 어떨까 합니다! 게임 대기와 시작 여부는 서버에서 실시간 통신으로 구현하는 방향으로 생각하고 있는데 수혁님은 어떻게 생각하시나요

**Comment by kwonsuhyuk** [comment]
음 근데 그렇게 하면 그 게임시작 전 대기화면이랑 게임시작하고 화면이랑 똑같아야 하지 않나요??

**Comment by nyh98** [comment]
넵 전 똑같은 화면에 대기화면일때 칠판 가운데 게임 시작 버튼을 통해서 게임 시작을 하는걸로 생각했습니다

**Comment by kwonsuhyuk** [comment]
아하 좋습니다
